In [1]:
from modules.data_services.data_utils import load_strategy_result

%load_ext autoreload
%autoreload 2

In [3]:
file_name = "returns_DOGEUSDT_ICPUSDT_2024-01-01_2024-02-01"
directory = "2026-01-25_09-30-03/1/test"

result = load_strategy_result(file_name, directory)

In [4]:
result.stats

                       gross     net
total_return          0.0144 -0.0057
cagr                  0.1826 -0.0651
volatility            0.0062  0.0062
volatility_annual     0.5766  0.5798
max_drawdown         -0.1390 -0.1440
win_count             5.0000  5.0000
lose_count            5.0000  5.0000
win_rate              0.5000  0.5000
max_win               0.0474  0.0463
max_lose             -0.0508 -0.0518
avg_win_return        0.0221  0.0209
avg_lose_return      -0.0192 -0.0202
avg_trade_return      0.0014  0.0003
sharpe_ratio          0.0060  0.0017
sharpe_ratio_annual   0.2994 -0.1296
sortino_ratio         0.0061  0.0018
sortino_ratio_annual  0.5750  0.1724
calmar_ratio          0.1034 -0.0397
calmar_ratio_annual   1.3141 -0.4523
objective             0.5750  0.1724

In [5]:
result.data

,DOGEUSDT,ICPUSDT,z_score,window,beta,entry_thr,exit_thr,sl_thr,q_x,q_y,w_x,w_y,signal,position,total_return,total_fees,net_return,total_return_pct,net_return_pct
open_time,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,0.08983,13.853,-0.904383,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000
2024-01-01 01:00:00,0.09016,13.693,-0.476936,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000
2024-01-01 02:00:00,0.08980,13.476,-0.922315,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000
2024-01-01 03:00:00,0.08921,13.313,-1.661238,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000
2024-01-01 04:00:00,0.08910,12.917,-1.781342,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-31 20:00:00,0.07900,11.584,-1.399173,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1436.845026,2007.840327,-570.995301,0.014368,-0.00571
2024-01-31 21:00:00,0.07883,11.454,-1.560146,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1436.845026,2007.840327,-570.995301,0.014368,-0.00571
2024-01-31 22:00:00,0.07879,11.482,-1.585771,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1436.845026,2007.840327,-570.995301,0.014368,-0.00571
2024-01-31 23:00:00,0.07875,11.471,-1.609780,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1436.845026,2007.840327,-570.995301,0.014368,-0.00571
2024-02-01 00:00:00,0.07905,11.575,-1.320422,67.0,-0.003777,2.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1436.845026,2007.840327,-570.995301,0.014368,-0.00571